# R-013 in the public sandbox, after the fresh-eyes review: make a list from a bill page (the sheet says what happened
# inside itself), see it in My issues, share it (one press makes and copies the link), the maker's ⋯ menu (Take bills
# off with Undo, Edit name and note, Remove with Undo), someone else's list (says it isn't HIPHI's), an empty list,
# the wide frame, and on a phone: the bottom sheet, the first bill high on the page, nothing too wide.
# Nothing is saved anywhere but this browser.
#   python3 tests/lists.py [base] [shots]      base defaults to http://localhost:8832/track.html?demo=1 (the published sandbox works too)
import sys, re, os
from playwright.sync_api import sync_playwright
BASE = sys.argv[1] if len(sys.argv) > 1 else 'http://localhost:8832/track.html?demo=1'
SHOTS = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(os.path.abspath(__file__)), 'out')
res = []
def ok(c, m): res.append(bool(c)); print('PASS' if c else 'FAIL', m)
def ready(pg):
    pg.wait_for_function("() => !!document.querySelector('main') && !document.querySelector('.skelpage')", timeout=60000); pg.wait_for_timeout(500)
SKIP = "() => { try { const w = JSON.parse(localStorage.getItem('hiphi_wiz') || '{}'); localStorage.setItem('hiphi_wiz', JSON.stringify({ ...w, done: true, step: 99 })); localStorage.setItem('hiphi_tour_bill', '{\"how\":\"test\"}'); localStorage.setItem('hiphi_tour_home', '{\"how\":\"test\"}'); } catch {} }"
def toast(pg): return pg.locator('.toastmsg').first.inner_text() if pg.locator('.toastmsg').count() else ''
with sync_playwright() as p:
    br = p.chromium.launch()
    ctx = br.new_context(viewport={'width': 1280, 'height': 900})
    ctx.grant_permissions(['clipboard-read', 'clipboard-write'])
    pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(BASE + '#/'); ready(pg); pg.evaluate(SKIP)
    nums = pg.evaluate("async () => { const c = await import('./pub/core.js'); return (c.D.bills || []).filter(b => b.bill_number).slice(0, 3).map(b => b.bill_number); }")
    num = nums[0]
    pg.goto(BASE + f'#/bill/{num}'); ready(pg)
    add = pg.locator('[data-bl-addto]').first
    ok(add.count() == 1 and add.is_visible(), f'the bill page ({num}) offers Add to a list on a laptop')
    add.click(); pg.wait_for_timeout(500)
    dlg = pg.locator('dialog.ul-sheet[open]')
    ok(dlg.count() == 1 and 'to a list' in dlg.locator('h2').inner_text(), 'the sheet opens: ' + (dlg.locator('h2').inner_text() if dlg.count() else ''))
    ok('private until you share' in dlg.inner_text() and 'You follow the bills on your lists' in dlg.inner_text(), 'the sheet says lists start private and their bills are followed')
    dlg.locator('#ul-newt').fill('Bills for my class')
    dlg.locator('[data-ulnewform] button[type=submit]').first.click(); pg.wait_for_timeout(600)
    ok(dlg.locator('[data-ulpick]').count() == 1 and dlg.locator('[data-ulpick]').first.is_checked(), 'a new list is made with the bill on it (ticked)')
    st = dlg.locator('#ul-shstat').inner_text()
    ok('Made Bills for my class and added' in st, f'the sheet itself says what happened: "{st}"')
    dlg.locator('[data-ulpick]').first.uncheck(); pg.wait_for_timeout(400)
    ok('Taken off Bills for my class' in dlg.locator('#ul-shstat').inner_text(), 'unticking says it was taken off')
    dlg.locator('[data-ulpick]').first.check(); pg.wait_for_timeout(400)
    ok('Added to Bills for my class' in dlg.locator('#ul-shstat').inner_text() and pg.locator('dialog.ul-sheet[open] [data-ulpick]').first.evaluate('e => document.activeElement === e'), 'ticking again says added, and focus stays on the box')
    dlg.locator('[data-uldone]').first.click(); pg.wait_for_timeout(400)
    ok(pg.locator('dialog.ul-sheet[open]').count() == 0, 'Done closes the sheet')
    ol = pg.locator('.bl-onlist').first
    ok(ol.count() == 1 and 'Bills for my class' in ol.inner_text(), 'the bill page now says it is on your list: ' + (ol.inner_text() if ol.count() else ''))
    # a second bill on the list, for Take off later; and a name typed then Done makes that list (C-9)
    pg.goto(BASE + f'#/bill/{nums[1]}'); ready(pg); pg.locator('[data-bl-addto]').first.click(); pg.wait_for_timeout(400)
    pg.locator('dialog.ul-sheet[open] [data-ulpick]').first.check(); pg.wait_for_timeout(400)
    pg.locator('dialog.ul-sheet[open] #ul-newt').fill('Typed then Done')
    pg.locator('dialog.ul-sheet[open] [data-uldone]').click(); pg.wait_for_timeout(600)
    ok(pg.locator('dialog.ul-sheet[open]').count() == 0 and 'Typed then Done' in pg.locator('.bl-onlist').inner_text(), 'a name typed then Done makes that list and adds the bill, then closes')
    # an error in the sheet is red, right under the lists: fill the first list to its 200-bill cap
    pg.evaluate("async () => { const c = await import('./pub/core.js'); const l = c.S.ul.mine.find(x => x.title === 'Typed then Done'); l.bill_ids = [...l.bill_ids, ...Array.from({ length: 199 }, (_, i) => 'x' + i)]; }")
    pg.goto(BASE + f'#/bill/{nums[2]}'); ready(pg); pg.locator('[data-bl-addto]').first.click(); pg.wait_for_timeout(400)
    pg.locator('dialog.ul-sheet[open] label:has-text("Typed then Done") input').click(); pg.wait_for_timeout(400)
    stat = pg.locator('#ul-shstat')
    ok('200 bills' in stat.inner_text() and 'bad' in (stat.get_attribute('class') or '') and pg.evaluate("document.querySelector('#ul-shstat').previousElementSibling.querySelector('.ul-pick') !== null"),
      'a failure shows in red under the lists: ' + stat.inner_text())
    pg.locator('dialog.ul-sheet[open] [data-uldone]').click(); pg.wait_for_timeout(300)
    pg.goto(BASE + '#/bills'); ready(pg)
    ok(pg.locator('#ul-mine-h').count() == 1 and 'Bills for my class' in pg.locator('main').inner_text(), 'My issues shows Your lists with it')
    pg.locator('a.row:has-text("Bills for my class")').first.click(); ready(pg)
    ok(pg.locator('h1').inner_text() == 'Bills for my class' and 'Private' in pg.locator('main .meta').first.inner_text(), 'its page: name, and private')
    ok(pg.locator('main .mb-row').count() == 2, 'both bills are on it')
    hb = pg.evaluate("(() => { const h = document.querySelector('.ul h1').getBoundingClientRect(), b = document.querySelector('.ul-actions .btn').getBoundingClientRect(); return [Math.round(h.top), Math.round(h.bottom), Math.round(b.top)]; })()")
    ok(hb[2] < hb[1], f'on a laptop the actions sit beside the title (title {hb[0]}-{hb[1]}, button at {hb[2]})')
    print('INFO laptop, unshared: first bill at', pg.evaluate("Math.round(document.querySelector('main .mb-row, main .mb-fold').getBoundingClientRect().top)"))
    mw = pg.evaluate("getComputedStyle(document.querySelector('main')).maxWidth")
    ok(mw == '1120px', f'a laptop gets the wide frame (main {mw})')
    ok(pg.locator('[data-ulsharemake]').count() == 1 and pg.locator('[data-ulmenu]').count() == 1, 'one row: Share this list and the ⋯ menu')
    pg.locator('[data-ulsharemake]').click(); pg.wait_for_timeout(900)
    url = pg.evaluate("navigator.clipboard.readText()")
    ok(re.search(r'#/l/[0-9a-f]{40}$', url), f'Share makes a link nobody can guess and copies it: …{url[-50:]}')
    t = toast(pg); ok('link is copied' in t, f'and says so: "{t.splitlines()[0] if t else ""}"')
    ok('Shared by link' in pg.locator('main .meta').first.inner_text() and pg.locator('[data-ulcopy]').count() == 1, 'the page now says it is shared and offers Copy link')
    ok(pg.locator('#ul-url').count() == 0, 'no link box when copying worked')
    lid = pg.evaluate("document.querySelector('.ul').dataset.list")
    tok = url.split('#/l/')[-1]
    pg.goto(BASE + f'#/l/{tok}'); ready(pg)
    ok(pg.locator('h1').inner_text() == 'Bills for my class' and pg.locator('[data-ulmenu]').count() == 1 and pg.locator('.ul-notus').count() == 0, 'the maker opening their own link gets their own page')
    pg.goto(BASE + f'#/mylist/{lid}'); ready(pg)
    # the ⋯ menu
    pg.locator('[data-ulmenu]').click(); pg.wait_for_timeout(200)
    mt = pg.locator('#ul-menu').inner_text() if pg.locator('#ul-menu').is_visible() else ''
    ok(all(x in mt for x in ['Stop sharing', 'Edit name and note', 'Take bills off', 'Remove list']), 'the ⋯ menu: ' + ' | '.join(mt.split('\n')))
    ok(pg.evaluate("document.activeElement.closest('#ul-menu') !== null"), 'opening it puts focus on its first item')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(150)
    ok(not pg.locator('#ul-menu').is_visible() and pg.evaluate("document.activeElement.matches('[data-ulmenu]')"), 'Escape closes it and focus goes back to ⋯')
    # Stop sharing, then Undo: the same link comes back
    pg.locator('[data-ulmenu]').click(); pg.locator('#ul-menu [data-ulunshare]').click(); pg.wait_for_timeout(500)
    ok('Private' in pg.locator('main .meta').first.inner_text(), 'Stop sharing makes it private')
    pg.locator('.toastmsg button:has-text("Undo")').first.click(); pg.wait_for_timeout(500)
    tok3 = pg.locator('[data-ulcopy]').get_attribute('data-ulcopy') if pg.locator('[data-ulcopy]').count() else ''
    ok(tok3 == tok and 'Shared by link' in pg.locator('main .meta').first.inner_text(), 'Undo brings back the same link')
    # Take bills off
    pg.locator('[data-ulmenu]').click(); pg.locator('#ul-menu [data-ultaking]').click(); pg.wait_for_timeout(300)
    ok(pg.locator('.ul-taking').count() == 1 and pg.locator('[data-ultake]').count() == 2 and pg.locator('main [data-star]').count() == 0, 'Take bills off: each row\'s star becomes a minus button, with a bar saying so')
    ok(pg.evaluate("document.activeElement.matches('[data-ultake]')"), 'focus moves to the first minus button')
    hdr = pg.locator('main .mb-hstar').first.inner_text()
    ok(hdr == 'Take off', f'the table header says it: "{hdr}"')
    pg.locator('[data-ultake]').first.click(); pg.wait_for_timeout(600)
    ok(pg.locator('main .mb-row').count() == 1, 'one press takes a bill off')
    t = toast(pg); ok('Undo' in t and 'still follow' in t, f'with Undo, and it says the bill is still followed: "{t.splitlines()[0] if t else ""}"')
    ok(pg.evaluate("document.activeElement.matches('[data-ultake]')"), 'focus moves to the next minus button')
    pg.locator('.toastmsg button:has-text("Undo")').first.click(); pg.wait_for_timeout(600)
    ok(pg.locator('main .mb-row').count() == 2, 'Undo puts it back')
    pg.locator('.ul-taking [data-ultaking]').click(); pg.wait_for_timeout(300)
    ok(pg.locator('.ul-taking').count() == 0 and pg.locator('main [data-star]').count() == 2, 'Done ends it: the stars come back')
    # Edit name and note
    pg.locator('[data-ulmenu]').click(); pg.locator('#ul-menu [data-uledit]').click(); pg.wait_for_timeout(200)
    pg.locator('#ul-t').fill('Bills for room 12'); pg.locator('#ul-n').fill('From Ms. K'); pg.locator('[data-ulsave] button[type=submit]').click(); pg.wait_for_timeout(400)
    ok(pg.locator('h1').inner_text() == 'Bills for room 12' and 'From Ms. K' in pg.locator('main .lede').first.inner_text(), 'Edit name and note saves both')
    pg.screenshot(path=f'{SHOTS}/ul_mine_1280.png')
    # someone else's list, as a stranger with the link sees it (made here: the sandbox has only this browser's lists)
    pg.evaluate("""async (ids) => { const c = await import('./pub/core.js'); c.S.ul.shared['f'.repeat(40)] = { id: 'x1', title: 'Teacher picks', note: 'Bills I care about',
      bill_ids: ids, followers: null, mine: false, following: false }; location.hash = '#/l/' + 'f'.repeat(40); }""", pg.evaluate("async () => { const c = await import('./pub/core.js'); return (c.D.bills || []).slice(0, 3).map(b => b.id); }"))
    ready(pg)
    m = pg.locator('main').inner_text()
    ok('not by HIPHI' in pg.locator('.ul-notus').inner_text() and 'Their note:' in m, 'someone else\'s list says, above its name, that HIPHI did not make it, and labels their note')
    ok(pg.locator('.fd-icon.ul-theirs').count() == 1 and pg.locator('[data-ulmenu]').count() == 0, 'it has a grey list icon and no maker\'s menu')
    ok(pg.locator('.hnav a[aria-current]').count() == 0, 'no tab claims a stranger\'s list')
    pg.locator('[data-ulfollow]').click(); pg.wait_for_timeout(700)
    ok('You follow this list' in pg.locator('main').inner_text(), 'Follow this list works')
    ok(pg.locator('.toastmsg').count() == 0 or 'follow' not in toast(pg).lower(), 'and is confirmed once, by the card (no second toast)')
    pg.screenshot(path=f'{SHOTS}/ul_theirs_1280.png')
    # Remove, with Undo
    pg.goto(BASE + f'#/mylist/{lid}'); ready(pg)
    pg.locator('[data-ulmenu]').click(); pg.locator('#ul-menu [data-ulremove]').click(); pg.wait_for_timeout(600)
    ok(pg.url.endswith('#/bills') and 'Bills for room 12' not in pg.locator('main').inner_text(), 'Remove list takes it off My issues')
    pg.locator('.toastmsg button:has-text("Undo")').first.click(); pg.wait_for_timeout(700)
    ok('Bills for room 12' in pg.locator('main').inner_text(), 'Undo brings it back')
    # an empty list, made from My issues
    pg.goto(BASE + '#/bills'); ready(pg)
    pg.locator('[data-ulnew]').first.click(); pg.wait_for_timeout(300)
    pg.locator('dialog.ul-sheet[open] #ul-newt').fill('Later'); pg.locator('dialog.ul-sheet[open] [data-ulmake] button[type=submit]').click(); pg.wait_for_timeout(600)
    ok(pg.locator('h1').inner_text() == 'Later' and pg.locator('[data-ulfind]').count() == 1 and pg.locator('[data-ulsharemake]').count() == 0, 'an empty list leads with Find bills to add, and no Share yet')
    ok('Add bills from any bill’s page' in pg.locator('.ul-say').inner_text(), 'and says where bills are added')
    pg.locator('[data-ulmenu]').click(); pg.wait_for_timeout(150)
    ok('Take bills off' not in pg.locator('#ul-menu').inner_text(), 'an empty list\'s menu has no Take bills off')
    ok(not errs, f'no page errors {errs[:3]}')
    ctx.close()
    # phone
    ph = br.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True)
    ph.grant_permissions(['clipboard-read', 'clipboard-write'])
    pp = ph.new_page(); perr = []; pp.on('pageerror', lambda e: perr.append(str(e)))
    pp.goto(BASE + '#/'); ready(pp); pp.evaluate(SKIP)
    pp.goto(BASE + f'#/bill/{num}'); ready(pp)
    pp.locator('[data-bl-menu]').click(); pp.wait_for_timeout(200)
    mi = pp.locator('#bl-menu [data-bl-addto]')
    ok(mi.count() == 1 and mi.is_visible(), 'on a phone the ⋯ menu has Add to a list')
    mi.click(); pp.wait_for_timeout(500)
    d = pp.locator('dialog.ul-sheet[open]')
    box = d.bounding_box() if d.count() else None
    ok(box and abs(box['y'] + box['height'] - 844) < 2 and box['height'] < 700, f'it rises from the bottom as tall as it needs ({int(box["height"]) if box else "?"}px)')
    d.locator('#ul-newt').fill('Phone list'); d.locator('[data-ulnewform] button[type=submit]').first.click(); pp.wait_for_timeout(600)
    ok('Made Phone list' in d.locator('#ul-shstat').inner_text(), 'the status shows inside the sheet on a phone too')
    ok(pp.evaluate("document.documentElement.scrollWidth") <= 390, 'nothing wider than the phone')
    pp.screenshot(path=f'{SHOTS}/ul_sheet_390.png')
    d.locator('[data-uldone]').first.click(); pp.wait_for_timeout(300)
    pp.goto(BASE + '#/bills'); ready(pp); pp.locator('a.row:has-text("Phone list")').first.click(); ready(pp)
    print('INFO phone, unshared: first bill at', pp.evaluate("Math.round(document.querySelector('main .mb-row, main .mb-fold').getBoundingClientRect().top)"))
    pp.locator('[data-ulsharemake]').click(); pp.wait_for_timeout(900)
    top = pp.evaluate("Math.round(document.querySelector('main .mb-row').getBoundingClientRect().top)")
    ok(top <= 400, f'a shared list\'s first bill starts at {top}px on a phone (A-1: 400)')
    ok(pp.evaluate("document.documentElement.scrollWidth") <= 390, 'the list page is no wider than the phone')
    pp.screenshot(path=f'{SHOTS}/ul_mine_390.png')
    pp.evaluate("""async (ids) => { const c = await import('./pub/core.js'); c.S.ul.shared['e'.repeat(40)] = { id: 'x2', title: 'Teacher picks', note: 'Bills I care about',
      bill_ids: ids, followers: null, mine: false, following: false }; location.hash = '#/l/' + 'e'.repeat(40); }""", pp.evaluate("async () => { const c = await import('./pub/core.js'); return (c.D.bills || []).slice(0, 3).map(b => b.id); }"))
    ready(pp)
    top2 = pp.evaluate("Math.round((document.querySelector('main .mb-row') || document.querySelector('main .mb-fold')).getBoundingClientRect().top)")
    print(f'INFO someone else\'s list on a phone: first bill at {top2}px')
    pp.screenshot(path=f'{SHOTS}/ul_theirs_390.png')
    pp.goto(BASE + '#/bills'); ready(pp); pp.locator('[data-ulnew]').first.click(); pp.wait_for_timeout(300)
    pp.locator('dialog.ul-sheet[open] #ul-newt').fill('Empty one'); pp.locator('dialog.ul-sheet[open] [data-ulmake] button[type=submit]').click(); pp.wait_for_timeout(600)
    ok('Add bills from any bill’s page' in pp.locator('.ul-say').inner_text(), 'on a phone the empty list says where bills are added')
    ok(not perr, f'phone: no page errors {perr[:2]}')
    br.close()
print(f"\n{sum(res)} passed, {len(res) - sum(res)} failed")
