#!/usr/bin/env node
// Regenerates icons.js from Lucide (lucide-static, pinned), keeping every icon already in it.
//   node tools/icons.mjs                 re-fetch the current set
//   node tools/icons.mjs star,calendar   add icons by name (see https://lucide.dev/icons)
// Inline SVG paths, so the pages need no icon font and make no request for icons. Lucide is ISC-licensed; the
// licence text stays at the top of icons.js.
import { readFileSync, writeFileSync } from 'node:fs';
const VER = '1.47.0';
const file = new URL('../icons.js', import.meta.url);
const current = Object.keys(JSON.parse((readFileSync(file, 'utf8').match(/export const ICONS = (\{[\s\S]*?\});/) || [, '{}'])[1]));
const wanted = [...new Set([...current, ...(process.argv[2] || '').split(',').map(s => s.trim()).filter(Boolean)])];
const paths = {}, missing = [];
for (const n of wanted) {
  const r = await fetch(`https://cdn.jsdelivr.net/npm/lucide-static@${VER}/icons/${n}.svg`);
  if (!r.ok) { missing.push(n); continue; }
  paths[n] = (await r.text()).match(/<svg[^>]*>([\s\S]*)<\/svg>/)[1].replace(/\s+/g, ' ').replace(/ \/>/g, '/>').trim();
}
const out = `// Interface icons: Lucide v${VER} (https://lucide.dev), ISC licence, inlined so the page needs no icon font or
// network request. Generated by tools/icons.mjs; add a name there rather than editing by hand.
// ISC License: Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather (MIT). All other
// copyright (c) for Lucide are held by Lucide Contributors 2022. Permission to use, copy, modify, and/or distribute this
// software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this
// permission notice appear in all copies.
export const ICONS = ${JSON.stringify(paths, null, 0).replace(/","/g, '",\n"')};
// icon('calendar') -> an inline SVG sized to the text (1.25em), decorative unless a label is given.
export function icon(name, { size = '1.25em', label = '', cls = '' } = {}) {
  const p = ICONS[name] || ICONS['circle'] || '';
  return \`<svg class="ic ic-\${name}\${cls ? ' ' + cls : ''}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${label ? \`role="img" aria-label="\${label.replace(/"/g, '&quot;')}"\` : 'aria-hidden="true" focusable="false"'}>\${p}</svg>\`;
}
`;
writeFileSync(file, out);
console.log(`icons.js: ${Object.keys(paths).length} icons${missing.length ? `; not found: ${missing.join(', ')}` : ''}`);
